// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASiyGFmgaSH3uFswNSOSjo3lpU4UsUQ-Y',
    appId: '1:1005452562779:web:4ee85fc54d98205d050a7e',
    messagingSenderId: '1005452562779',
    projectId: 'fruits-hup-604c1',
    authDomain: 'fruits-hup-604c1.firebaseapp.com',
    storageBucket: 'fruits-hup-604c1.firebasestorage.app',
    measurementId: 'G-VNBSCMS8QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyGoFfeB9w60m-nWEuvg-ldsXSqg1ogng',
    appId: '1:1005452562779:android:35d6cee1f410ac6f050a7e',
    messagingSenderId: '1005452562779',
    projectId: 'fruits-hup-604c1',
    storageBucket: 'fruits-hup-604c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsEaOhxThh7mKMEmc0Gz1l-f0ywD-Snio',
    appId: '1:1005452562779:ios:d4bb1aa43c834493050a7e',
    messagingSenderId: '1005452562779',
    projectId: 'fruits-hup-604c1',
    storageBucket: 'fruits-hup-604c1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsEaOhxThh7mKMEmc0Gz1l-f0ywD-Snio',
    appId: '1:1005452562779:ios:d4bb1aa43c834493050a7e',
    messagingSenderId: '1005452562779',
    projectId: 'fruits-hup-604c1',
    storageBucket: 'fruits-hup-604c1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASiyGFmgaSH3uFswNSOSjo3lpU4UsUQ-Y',
    appId: '1:1005452562779:web:398a2a3bad587eca050a7e',
    messagingSenderId: '1005452562779',
    projectId: 'fruits-hup-604c1',
    authDomain: 'fruits-hup-604c1.firebaseapp.com',
    storageBucket: 'fruits-hup-604c1.firebasestorage.app',
    measurementId: 'G-WPWT7054FF',
  );
}
